#pragma once
#include <fstream>

class MyString;

namespace GameConstants {
	const int MIN_CAPACITY = 4;
	const int BUFFER_CAPACITY = 1024;
	const int INITIAL_MONEY = 1500;
	const int MAX_PLAYERS = 6;
	const int RENT_TIERS_COUNT = 7;
	const int JAIL_POSITION = 10;
	const int MAX_ROLLS = 3;
	const int BOARD_SIZE = 40;
	const int INVALID_POSITION = -1;
	const int INVALID_PLAYER_ID = -1;
	const int START_RENT_TIER = 0;
	const int GO_TO_JAIL_FIELD_INDEX = 30;
	const int PARKING_FIELD_INDEX = 20;
	const int GO_FIELD_INDEX = 0;
	const int JAIL_FIELD_INDEX = 10;
	const int PASS_GO_BONUS = 200;
	const int PRINT_BOARD_WIDTH = 11;
	const int CELL_WIDTH = 20;
	const int ILLINOIS_LOCATION = 24;
	const int ST_CHARLES_LOCATION = 11;
	const int TOTAL_STATIONS = 4;
	const int TOTAL_UTILITIES = 2;
	const int READING_RAILROAD_LOCATION = 5;
	const int PENNSYLVANIA_RAILROAD_LOCATION = 15;
	const int BO_RAILROAD_LOCATION = 25;
	const int SHORT_LINE_RAILROAD_LOCATION = 35;
	const int ELECTRIC_COMPANY_LOCATION = 12;
	const int WATER_WORKS_LOCATION = 28;
	const int BROADWALK_LOCATION = 39;
	const int BANK_DIVIDENT_REWARD = 50;
	const int REPAIR_HOUSE_PRICE = 25;
	const int REPAIR_HOTEL_PRICE = 100;
	const int POOR_TAX = 15;
	const int BANK_ERROR_REWARD = 200;
	const int DOCTOR_FEE = 50;
	const int SALE_OF_STOCK_REWARD = 50;
	const int HOLIDAY_FUNDS_REWARD = 100;
	const int INCOME_TAX_REFUND = 20;
	const int BIRTHDAY_REWARD = 10;
	const int LIFE_INSURANCE = 100;
	const int HOSPITAL_FEE = 50;
	const int SCHOOL_FEE = 50;
	const int CONSULTANCY_FEE_REWARD = 25;
	const int INHERITANCE_REWARD = 100;
	const int ASSESSED_HOUSE_REPAIR_PRICE = 40;
	const int ASSESSED_HOTEL_REPAIR_PRICE = 115;
	const int GRAND_OPERA_NIGHT_REWARD = 50;
	const int BEAUTY_CONTEST_REWARD = 10;
	const int LOAN_MATURES_REWARD = 150;
	const int CHAIRMAN_OF_THE_BOARD_AMOUNT = 50;
	const int FIRST_AND_LAST_PROPERTIES_COUNT_BY_COLOR = 2;
	const int REST_PROPERTIES_COUNT_BY_COLOR_ = 3;
	const int STATION_FIRST_RENT = 25;
	const int STATION_SECOND_RENT = 50;
	const int STATION_THIRD_RENT = 100;
	const int STATION_FOURTH_RENT = 200;
	const int RENT_TIERS_STATION_COUNT = 4;
	const int RAILROAD_PRICE = 200;
	const int JAIL_RELEASE_PRICE = 50;
	const int TIMES_TO_ROLL_IN_JAIL = 3;
	const int UTILITY_FIRST_MULTIPLIER = 4;
	const int UTILITY_SECOND_MULTIPLIER = 10;
	const int FIRST_BUILDING_RENT_INDEX = 2;
	const int COLOR_SET_RENT_INDEX = 1;
	const int HOTEL_BUILDING_NUM = 5;
	const int HALF_PRICE_MULTIPLIER = 2;
	const int RELEASE_CARDS_INITIAL_VALUE = 0;
	const int INITIAL_OWED_MONEY = 0;
};
